root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o tmp/main ./cmd/evolyte-energy-provider-adapter/main.go"
  include = ["*.go"]
  exclude = ["tmp", "vendor"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  log = "white"