FROM golang:1.24-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

WORKDIR /app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main ./cmd/evolyte-energy-provider-adapter/main.go

EXPOSE 8002

CMD ["air"]